name: "flake build"

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target: [ "24.11", "unstable" ]

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31

      - uses: DeterminateSystems/magic-nix-cache-action@v9
        with:
          diagnostic-endpoint: false
          use-flakehub: false

      - name: build stable
        if: matrix.target != 'unstable'
        run: |
          nix build -L \
            --override-input nixpkgs github:NixOS/nixpkgs/nixos-${{ matrix.target }}

      - name: build unstable
        if: matrix.target == 'unstable'
        run: |
          nix build -L
