name: "flake build"

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target: [ "25.05", "unstable" ]

    steps:
      - uses: actions/checkout@v4

      # NOTE: not using the nix-daemon causes different hashes in FOD
      # - name: Install Nix
      #   uses: nixbuild/nix-quick-install-action@v30
      #
      # - uses: nix-community/cache-nix-action@v6
      #   with:
      #     primary-key: nix-${{ runner.os }}-${{ matrix.target }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
      #     restore-prefixes-first-match: nix-${{ runner.os }}-${{ matrix.target }}-
      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: build stable
        if: matrix.target != 'unstable'
        run: |
          nix build -L \
            --override-input nixpkgs github:NixOS/nixpkgs/nixos-${{ matrix.target }}

      - name: build unstable
        if: matrix.target == 'unstable'
        run: |
          nix build -L
